name: Schedule Job

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Schedule Workflow Executed"
